version: "3"
services:
  app:
    build:
      context: .
      dockerfile: compose/Dockerfile.dev
      args:
        API_URL: http://localhost:9090
    container_name: app
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/src/app/shared/environment
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
