FROM public.ecr.aws/docker/library/node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --silent

COPY ./ ./

RUN npm run build --prod

FROM public.ecr.aws/docker/library/nginx:alpine

EXPOSE 80

COPY ./compose/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/quiz-stream/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]