FROM node:20

ARG API_URL

ENV API_URL=${API_URL}

EXPOSE 4200

WORKDIR /app

COPY ./ ./

RUN npm install

RUN npm install -g @angular/cli

RUN ng analytics off

RUN sed -i "s|API_URL|${API_URL}|g" src/app/shared/environment/environment.ts

ENTRYPOINT ["sh", "-c", "ng serve --host 0.0.0.0 --poll 2000"]